version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4321:4321
    command: ["npm", "run", "dev", "--", "--host"]